"""
Upload APK to Google Drive using a service account and write share link to file.

Required environment variables (set via GitHub Secrets):
  GDRIVE_SERVICE_ACCOUNT_JSON  - Full service account JSON content
  GDRIVE_FOLDER_ID             - Destination Google Drive folder ID
  APK_NAME                     - APK filename generated by workflow
"""

from __future__ import annotations

import json
import os
import sys

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload


def fail(msg: str) -> None:
    print(f"::error::{msg}")
    sys.exit(1)


def main() -> None:
    raw_json = (os.environ.get("GDRIVE_SERVICE_ACCOUNT_JSON") or "").strip()
    folder_id = (os.environ.get("GDRIVE_FOLDER_ID") or "").strip()
    apk_name = (os.environ.get("APK_NAME") or "app-release.apk").strip()

    if not raw_json:
        fail("GDRIVE_SERVICE_ACCOUNT_JSON secret is missing")
    if not folder_id:
        fail("GDRIVE_FOLDER_ID secret is missing")
    if not os.path.isfile(apk_name):
        fail(f"APK file not found: {apk_name}")

    try:
        service_info = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        fail(f"Invalid GDRIVE_SERVICE_ACCOUNT_JSON: {exc}")
        return

    creds = service_account.Credentials.from_service_account_info(
        service_info,
        scopes=["https://www.googleapis.com/auth/drive"],
    )
    drive = build("drive", "v3", credentials=creds)

    metadata = {
        "name": apk_name,
        "parents": [folder_id],
    }
    media = MediaFileUpload(apk_name, mimetype="application/vnd.android.package-archive")

    print(f"📤 Uploading {apk_name} to Google Drive…")
    created = (
        drive.files()
        .create(body=metadata, media_body=media, fields="id,name,webViewLink,webContentLink")
        .execute()
    )

    file_id = created["id"]

    # Make file accessible for anyone with link
    drive.permissions().create(
        fileId=file_id,
        body={"type": "anyone", "role": "reader"},
    ).execute()

    download_link = f"https://drive.google.com/file/d/{file_id}/view?usp=sharing"

    with open("gdrive_link.txt", "w", encoding="utf-8") as f:
        f.write(download_link)

    github_output = os.environ.get("GITHUB_OUTPUT", "")
    if github_output:
        with open(github_output, "a", encoding="utf-8") as f:
            f.write(f"gdrive_link={download_link}\n")

    print("✅ Uploaded to Google Drive")
    print(f"🔗 {download_link}")


if __name__ == "__main__":
    main()
