query MyReservation($id: ID!) {
  myReservation(id: $id) {
    id
    status
    createdAt
    confirmedAt
    updatedAt
    beneficiaryId
    beneficiary {
      id
      displayName
      avatar {
        url
      }
    }
    donation {
      id
      createdAt
      title
      description
      quantity
      categoryId
      category {
        id
        name
      }
      status
      urgency
      isLikedByMe
      isReservable
      expiryDate
      publishedAt
      locationId
      location {
        latitude
        longitude
      }
      mainAttachmentId
      attachmentIds
      userId
      safetyChecklistCompleted
      listingExpiresAt
      updatedAt
      mainAttachment {
        id
        url
        fileName
        fileType
        fileSize
        createdAt
        updatedAt
        uploadStatus
        jobId
        uploadedById
      }
      user {
        id
        avatarAttachmentId
        createdAt
        description
        displayName
        email
        isMailVerified
        lastChangedPasswordDate
        locationId
        location {
          city
          country
          latitude
          longitude
          neighborhood
        }
        phoneNumber
        reputationScore
        role
        status
        updatedAt
        avatar {
          createdAt
          fileName
          fileSize
          fileType
          id
          jobId
          updatedAt
          uploadStatus
          uploadedById
          url
        }
      }
    }
  }
}
