query MyReservations($pagination: PaginationInput) {
  myReservations(pagination: $pagination) {
    hasNextPage
    hasPreviousPage
    totalCount
    page
    limit
    items {
      id
      status
      createdAt
      confirmedAt
      updatedAt
      donation {
        id
        title
        description
        quantity
        categoryId
        status
        urgency
        isLikedByMe
        expiryDate
        publishedAt
        locationId
        mainAttachmentId
        attachmentIds
        userId
        safetyChecklistCompleted
        listingExpiresAt
        updatedAt
        mainAttachment {
          id
          url
          fileName
          fileType
          fileSize
          createdAt
          updatedAt
          uploadStatus
          jobId
          uploadedById
        }
      }
    }
  }
}
