fragment ReservationFields on Reservation {
  id
  donationId
  beneficiaryId
  status
  createdAt
  confirmedAt
  updatedAt
  donation {
    id
    createdAt
    title
    description
    quantity
    categoryId
    category {
      id
      name
    }
    status
    urgency
    isLikedByMe
    isReservable
    safetyChecklistCompleted
    mainAttachmentId
    mainAttachment {
      url
    }
    locationId
    location {
      latitude
      longitude
    }
    user {
      id
      displayName
      email
      isVerified
      isFoodSaver
      avatar {
        id
        url
      }
    }
  }
  beneficiary {
    id
    email
    displayName
    phoneNumber
    role
    description
    isVerified
    isFoodSaver
    reputationScore
    locationId
    location {
      city
      country
      latitude
      longitude
      neighborhood
    }
    avatar {
      id
      url
    }
  }
}
