query LikedDonations($pagination: PaginationInput) {
  likedDonations(pagination: $pagination) {
    hasNextPage
    hasPreviousPage
    limit
    page
    totalCount
    items {
      id
      createdAt
      title
      description
      quantity
      categoryId
      category {
        id
        name
      }
      status
      urgency
      isLikedByMe
      expiryDate
      mainAttachmentId
      mainAttachment {
        url
      }
      locationId
      location {
        latitude
        longitude
      }
      user {
        displayName
        email
      }
    }
  }
}
