query GetDonations(
  $pagination: PaginationInput
  $filter: DonationsFilterInput
) {
  donations(pagination: $pagination, filter: $filter) {
    items {
      id
      createdAt
      title
      description
      quantity
      categoryId
      category {
        id
        name
      }
      status
      urgency
      isLikedByMe
      mainAttachmentId
      mainAttachment {
        url
      }
      locationId
      location {
        latitude
        longitude
      }
      user {
        displayName
        email
      }
    }
  }
}
